import { useMemo } from 'react'

/**
 * The eye of the finale whirlpool — a clean, geometric Celtic mandala.
 *
 * Rebuilt for legible RADIAL SYMMETRY (the old curved-running-text rings never
 * closed into circles and read as scattered hash). The skeleton is a set of clean
 * concentric keyline circles — they always read as rings — interleaved with
 * N-fold symmetric motif bands (petals, ticks, dots, spokes) generated by rotating
 * one motif around the centre. Two slow counter-rotating groups give life without
 * breaking symmetry; the finale scroll-jack owns the whole layer's spin + scale.
 * Ink + ember rim + a forge-glow core, with the fire-opal veins bleeding through
 * the gaps. Decorative — aria-hidden.
 */

// even angular divisions of the circle → true N-fold rotational symmetry
const ring = (n) => Array.from({ length: n }, (_, i) => (i * 360) / n)
// a pointed leaf/petal from radius ri to ro, half-width w, pointing outward (-y)
const petal = (ri, ro, w) =>
  `M0,${-ri} C${w},${-(ri + (ro - ri) * 0.4)} ${w},${-(ro - (ro - ri) * 0.18)} 0,${-ro}` +
  ` C${-w},${-(ro - (ro - ri) * 0.18)} ${-w},${-(ri + (ro - ri) * 0.4)} 0,${-ri} Z`

export default function Mandala() {
  // concentric keyline circles — the stable skeleton that ALWAYS reads as rings
  const circles = useMemo(() => [472, 408, 344, 280, 216, 152], [])
  const ticks = useMemo(() => ring(48), [])
  const petalsOuter = useMemo(() => ring(16), [])
  const dots = useMemo(() => ring(24), [])
  const petalsInner = useMemo(() => ring(12), [])
  const spokes = useMemo(() => ring(12), [])
  const word = 'GAELWORX · AUTOMATIC EXECUTION · CLAN PROTECTED · ONE FORGE · '

  return (
    <svg className="mandala-svg" viewBox="-500 -500 1000 1000" aria-hidden="true" preserveAspectRatio="xMidYMid meet">
      <defs>
        <radialGradient id="mWell">
          <stop offset="0" stopColor="#000" stopOpacity="0.8" />
          <stop offset="0.55" stopColor="#000" stopOpacity="0.5" />
          <stop offset="0.88" stopColor="#000" stopOpacity="0.12" />
          <stop offset="1" stopColor="#000" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="mBoss">
          <stop offset="0" stopColor="#E85D04" stopOpacity="0.95" />
          <stop offset="0.45" stopColor="#C1292E" stopOpacity="0.5" />
          <stop offset="1" stopColor="#0a0708" stopOpacity="0" />
        </radialGradient>
        {/* a full circle (clockwise from top) for the word rim */}
        <path id="mWordPath" d="M0,-440 A440,440 0 1,1 0,440 A440,440 0 1,1 0,-440 Z" />
      </defs>

      {/* the drain seat the problems pour into */}
      <circle r="500" fill="url(#mWell)" />

      {/* SKELETON — clean concentric keyline circles (these read as rings, always) */}
      <g className="m-rings">
        {circles.map((r, i) => (
          <circle key={i} className={i % 2 ? 'm-ring m-ring--ember' : 'm-ring'} r={r} />
        ))}
      </g>

      {/* OUTER band — slow turn one way */}
      <g className="m-spin m-spin--out">
        {/* word rim — overfilled so it closes the full circle (truncates, no gap) */}
        <text className="m-word">
          <textPath href="#mWordPath" startOffset="0">{word.repeat(5)}</textPath>
        </text>
        {/* fine rim ticks (48-fold) */}
        {ticks.map((a, i) => (
          <line key={i} className="m-tick" x1="0" y1="-396" x2="0" y2="-378" transform={`rotate(${a})`} />
        ))}
        {/* outer petals (16-fold) */}
        {petalsOuter.map((a, i) => (
          <path key={i} className="m-petal" d={petal(284, 344, 26)} transform={`rotate(${a})`} />
        ))}
      </g>

      {/* INNER band — slow turn the other way */}
      <g className="m-spin m-spin--in">
        {/* dot ring (24-fold) */}
        {dots.map((a, i) => (
          <circle key={i} className="m-dot" cx="0" cy="-248" r="5.5" transform={`rotate(${a})`} />
        ))}
        {/* inner petals (12-fold) */}
        {petalsInner.map((a, i) => (
          <path key={i} className="m-petal m-petal--in" d={petal(156, 212, 22)} transform={`rotate(${a})`} />
        ))}
        {/* radial spokes into the core (12-fold) */}
        {spokes.map((a, i) => (
          <line key={i} className="m-spoke" x1="0" y1="-148" x2="0" y2="-94" transform={`rotate(${a})`} />
        ))}
      </g>

      {/* central forge boss — fills the eye so it never reads hollow */}
      <g className="m-boss">
        <circle r="120" fill="url(#mBoss)" />
        <circle className="m-ring" r="92" />
        <circle className="m-ring m-ring--ember" r="44" />
        <circle className="m-core" r="14" />
      </g>
    </svg>
  )
}
